### ISSUE TITLE
sorting out elasticsearch/kibana

### ISSUE THREAD

**Issue by donsizemore** [DICE-UNC/de-ansible#17]
ansible/docker doesn't bring up elasticsearch/kibana OotB.

**Comment by michael-conway** [comment]
current renci vmlab4 box

docker inspect elastic search

``` JSON


[
{
    "Id": "696432ad30e22f45c3d1745bb89f1a296c4a389c29b6917cc0ee89544f9b7328",
    "Created": "2016-01-07T19:09:16.156185678Z",
    "Path": "/docker-entrypoint.sh",
    "Args": [
        "elasticsearch"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 880198,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-07T19:09:16.588794276Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "a05cc7ed3f3212298959069a6990b1b460821cc3dfdb363f356acf1dff73c961",
    "ResolvConfPath": "/var/lib/docker/containers/696432ad30e22f45c3d1745bb89f1a296c4a389c29b6917cc0ee89544f9b7328/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/696432ad30e22f45c3d1745bb89f1a296c4a389c29b6917cc0ee89544f9b7328/hostname",
    "HostsPath": "/var/lib/docker/containers/696432ad30e22f45c3d1745bb89f1a296c4a389c29b6917cc0ee89544f9b7328/hosts",
    "LogPath": "",
    "Name": "/elkelasticsearch",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/etc/iplant/de:/etc/iplant/de",
            "/etc/localtime:/etc/localtime",
            "/etc/timezone:/etc/timezone",
            "/etc/iplant/de/elk/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "9200/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "9200"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": [
            "elkdata"
        ],
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "syslog",
            "Config": {
                "syslog-tag": "elk-elasticsearch"
            }
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "19541",
            "DeviceName": "docker-253:2-8390006-696432ad30e22f45c3d1745bb89f1a296c4a389c29b6917cc0ee89544f9b7328",
            "DeviceSize": "107374182400"
        }
    },
    "Mounts": [
        {
            "Source": "/etc/timezone",
            "Destination": "/etc/timezone",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/etc/iplant/de/elk/elasticsearch.yml",
            "Destination": "/etc/elasticsearch/elasticsearch.yml",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "0be334039d176217039c55c973d7d5448e70e0c29dfbc55e31e76b460f886268",
            "Source": "/var/lib/docker/volumes/0be334039d176217039c55c973d7d5448e70e0c29dfbc55e31e76b460f886268/_data",
            "Destination": "/usr/share/elasticsearch/data",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/etc/iplant/de",
            "Destination": "/etc/iplant/de",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/etc/localtime",
            "Destination": "/etc/localtime",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "696432ad30e2",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": {
            "9200/tcp": {},
            "9300/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "ES_HEAP_SIZE=1g",
            "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "JAVA_VERSION=8u66",
            "JAVA_DEBIAN_VERSION=8u66-b17-1~bpo8+1",
            "CA_CERTIFICATES_JAVA_VERSION=20140324",
            "ELASTICSEARCH_MAJOR=2.1",
            "ELASTICSEARCH_VERSION=2.1.1",
            "ELASTICSEARCH_REPO_BASE=http://packages.elasticsearch.org/elasticsearch/2.x/debian"
        ],
        "Cmd": [
            "elasticsearch"
        ],
        "Image": "elasticsearch",
        "Volumes": {
            "/usr/share/elasticsearch/data": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/docker-entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "6ba0c91b83d974476150a8d1840211d837ff63c4bb93862130c3256456735445",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "9200/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "9200"
                }
            ],
            "9300/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/6ba0c91b83d9",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "2b58fbe20c32310010f1ec0dd8e7de0807b048e4b7295b8a632fff97e446c374",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "EndpointID": "2b58fbe20c32310010f1ec0dd8e7de0807b048e4b7295b8a632fff97e446c374",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:02"
            }
        }
    }
}
]


```

**Comment by michael-conway** [comment]
docker inspect elkkibana

``` JSON

[
{
    "Id": "4dbeb095c376df0e7b6143d595a63b1d18c5f55836a20f44643a7b2cc30d5d66",
    "Created": "2016-01-08T13:02:09.571112822Z",
    "Path": "/docker-entrypoint.sh",
    "Args": [
        "kibana"
    ],
    "State": {
        "Status": "exited",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 1,
        "Error": "",
        "StartedAt": "2016-01-08T13:02:09.90967706Z",
        "FinishedAt": "2016-01-08T13:02:16.162071495Z"
    },
    "Image": "171cd511944057f023437e8403b9b50ccc1a65116a19b64f26484e2575ca1fbd",
    "ResolvConfPath": "/var/lib/docker/containers/4dbeb095c376df0e7b6143d595a63b1d18c5f55836a20f44643a7b2cc30d5d66/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/4dbeb095c376df0e7b6143d595a63b1d18c5f55836a20f44643a7b2cc30d5d66/hostname",
    "HostsPath": "/var/lib/docker/containers/4dbeb095c376df0e7b6143d595a63b1d18c5f55836a20f44643a7b2cc30d5d66/hosts",
    "LogPath": "",
    "Name": "/elkkibana",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/etc/iplant/de:/etc/iplant/de",
            "/etc/localtime:/etc/localtime",
            "/etc/timezone:/etc/timezone"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "5601/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "5601"
                }
            ]
        },
        "Links": [
            "/elkelasticsearch:/elkkibana/elasticsearch"
        ],
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "syslog",
            "Config": {
                "syslog-tag": "elk-kibana"
            }
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "19549",
            "DeviceName": "docker-253:2-8390006-4dbeb095c376df0e7b6143d595a63b1d18c5f55836a20f44643a7b2cc30d5d66",
            "DeviceSize": "107374182400"
        }
    },
    "Mounts": [
        {
            "Source": "/etc/iplant/de",
            "Destination": "/etc/iplant/de",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/etc/localtime",
            "Destination": "/etc/localtime",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/etc/timezone",
            "Destination": "/etc/timezone",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "4dbeb095c376",
        "Domainname": "",
        "User": "",
        "AttachStdin": true,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": {
            "5601/tcp": {}
        },
        "Tty": false,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": [
            "PATH=/opt/kibana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "KIBANA_VERSION=4.1.2",
            "KIBANA_SHA1=45e67114f7dac4ccac8118bf98ee8f6362c7a6a1"
        ],
        "Cmd": [
            "kibana"
        ],
        "Image": "kibana:4.1.2",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": [
            "/docker-entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": {
            "bridge": {
                "EndpointID": "",
                "Gateway": "",
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": ""
            }
        }
    }
}
]




```

**Comment by michael-conway** [comment]
log from elkkibana startup

```

[root@dfc-test-vmlab4 elk]# docker run --name elkkibana         -v /etc/iplant/de:/etc/iplant/de         -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone         -p 5601:5601         --link elkelasticsearch:elasticsearch         --log-driver=syslog --log-opt syslog-tag=elk-kibana -i        kibana:4.1.2

{"name":"Kibana","hostname":"4dbeb095c376","pid":1,"level":50,"err":{"message":"unknown error","name":"Error","stack":"Error: unknown error\n    at respond (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:237:15)\n    at checkRespForFailure (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n    at HttpConnector.<anonymous> (/opt/kibana/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n    at IncomingMessage.bound (/opt/kibana/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)"},"msg":"","time":"2016-01-08T13:02:16.145Z","v":0}
{"name":"Kibana","hostname":"4dbeb095c376","pid":1,"level":60,"err":{"message":"unknown error","name":"Error","stack":"Error: unknown error\n    at respond (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:237:15)\n    at checkRespForFailure (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n    at HttpConnector.<anonymous> (/opt/kibana/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n    at IncomingMessage.bound (/opt/kibana/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:442:13)"},"msg":"","time":"2016-01-08T13:02:16.146Z","v":0}


```

**Comment by michael-conway** [comment]
nb kibana dockerhub

https://hub.docker.com/_/kibana/

github

https://github.com/docker-library/docs/tree/master/kibana

**Comment by michael-conway** [comment]
set to version 4.2 and problem disappears
